package es.munvi.hibernateannotated;
// Generated 13-sep-2015 20:11:28 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Clientes generated by hbm2java
 */
@Entity
@Table(name="clientes"
    ,catalog="eucip"
)
public class Clientes  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellido;
     private String ciudad;

    public Clientes() {
    }

	
    public Clientes(String dni) {
        this.dni = dni;
    }
    public Clientes(String dni, String nombre, String apellido, String ciudad) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido = apellido;
       this.ciudad = ciudad;
    }
   
     @Id 

    
    @Column(name="dni", unique=true, nullable=false, length=10)
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }

    
    @Column(name="nombre", length=45)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="apellido", length=45)
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }

    
    @Column(name="ciudad", length=45)
    public String getCiudad() {
        return this.ciudad;
    }
    
    public void setCiudad(String ciudad) {
        this.ciudad = ciudad;
    }




}


